" Plugins
filetype off " required
call plug#begin('~/.vim/plugged')
    " Status line
    Plug 'bling/vim-airline'

    " Themes for airline
    Plug 'vim-airline/vim-airline-themes'

    " Improved tree
    Plug 'scrooloose/nerdtree', { 'on': ['NERDTreeToggle', 'NERDTreeFind'] }

    " Github integration
    Plug 'tpope/vim-fugitive'

    " Automatic delimiter adding
    Plug 'Raimondi/delimitMate'

    " Class outline viewer
    Plug 'majutsushi/tagbar', { 'on': ['Tagbar'] }

    " Tab completion
    Plug 'ervandew/supertab'

    " Terraform
	Plug 'hashivim/vim-terraform', { 'for': [ 'terraform' ] }

	" Python
	Plug 'davidhalter/jedi-vim', { 'for': [ 'python' ] }

    " Inspect startup time of vim
    Plug 'tweekmonster/startuptime.vim'
call plug#end()

" Remove VI compatibility. SET FIRST!
set nocompatible

" http://lists.alioth.debian.org/pipermail/pkg-vim-maintainers/2007-June/004020.html
set modelines=0

" Unicode
set encoding=utf8

" show intermediate commands
set showcmd

" Set linenumbers
set number
set relativenumber

" Highlight search
set hlsearch

" Predictive search
set incsearch

" Show current position
set ruler

" Show matching brackets when text indicator is over them
set showmatch

" No backups
set noswapfile

" Enable syntax highlighting
if !exists("g:syntax_on")
    syntax enable
endif

" Enable 256 color mode
set t_Co=256

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Use spaces instead of tabs
set expandtab

" Smart tabs
set smarttab

" Tab spaces
set shiftwidth=4
set tabstop=4
set softtabstop=4

" Ident to the nearest tab
set shiftround

" whitespaces
highlight ExtraWhiteSpace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

" Plugins
runtime! config/**/*.vim
