set nocompatible                        " Remove VI compatibility. SET FIRST!

" Plugins
filetype off " required
call plug#begin('~/.vim/plugged')
    " Status line
    Plug 'bling/vim-airline'

    " Themes for airline
    Plug 'vim-airline/vim-airline-themes'

    " Automatic delimiter adding
    Plug 'Raimondi/delimitMate'

    " Github integration
    Plug 'tpope/vim-fugitive'

    " Improved tree
    Plug 'scrooloose/nerdtree', { 'on': ['NERDTreeToggle', 'NERDTreeFind'] }

    " Class outline viewer
    Plug 'majutsushi/tagbar', { 'on': ['Tagbar'] }

    " Tab completion
    Plug 'ervandew/supertab'

	" Inspect startup time of vim
    Plug 'tweekmonster/startuptime.vim'

	" Ruby
	Plug 'vim-ruby/vim-ruby', { 'for': [ 'ruby' ] }

    " Terraform
	Plug 'hashivim/vim-terraform', { 'for': [ 'terraform' ] }

	" Python
	Plug 'davidhalter/jedi-vim', { 'for': [ 'python' ] }
call plug#end()

" filetype [ON] plugin [ON] ident [ON]
filetype plugin indent on

" Turn on wildmenu
set wildmenu

" http://lists.alioth.debian.org/pipermail/pkg-vim-maintainers/2007-June/004020.html
set modelines=0

" Unicode
set encoding=utf8

" show intermediate commands
set showcmd

" Set linenumbers
set number

" Cursorline
set cursorline                          " Highlight cursor line
highlight CursorLineNR ctermbg=grey     " Set line numbering to grey background
highlight clear CursorLine              " Remove the underline from enabling cursorline

" Highlight search
set hlsearch

" Predictive search
set incsearch

" Show current position
set ruler

" Show matching brackets when text indicator is over them
set showmatch

" No backups
set noswapfile

" Enable syntax highlighting
if !exists("g:syntax_on")
    syntax enable
endif

" Enable 256 color mode
set t_Co=256

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Use spaces instead of tabs
set expandtab

" Smart tabs
set smarttab

" Tab spaces
set shiftwidth=4
set tabstop=4
set softtabstop=4

" Ident to the nearest tab
set shiftround

" whitespaces
highlight ExtraWhiteSpace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

" Plugins
runtime! config/*.vim
